name: flutter_dark_arch
description: '-'

version: 0.0.1+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 0.1.2
  permission_handler: 4.0.0
  # Architecture
  bloc_pattern: 2.5.1
  rxdart: 0.22.6
  stream_transform: 0.0.19
  path_provider: 1.5.0
  archive: 2.0.13
  # Logging
  logging: 0.11.3+2
  # Api
  chopper: 3.0.1
  jaguar_serializer: 2.2.12
  # Maps
  geolocator: 5.1.5
  google_maps_flutter: 0.5.21+13
  google_map_polyline: 0.2.0+1
  latlong: 0.6.1
  # Persistence
  floor: 0.9.0
  shared_preferences: 0.5.4+6
  rx_shared_preferences: 1.0.3+2
  # Date Formatting
  intl: 0.15.8
  # Qr scan
  flutter_barcode_scanner: 0.1.7
  # Camera
  camera: 0.5.7+1
  image: 2.1.10
  flutter_image_compress: 0.6.3
  # Speech recognition
  speech_recognition: 0.3.0+1
  # Video player
  video_player: 0.10.4+1
  configurable_expansion_tile: 1.0.0
  save_in_gallery: 0.1.3
  flushbar: 1.9.1
  align_positioned: ^1.2.5
  # Parse and format text
  flutter_parsed_text: 1.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.7.1
  # Generating Persistence
  jaguar_query_sqflite: 2.2.11
  # Generating Api
  chopper_generator: 3.0.0
  jaguar_serializer_cli: 2.2.8
  flutter_launcher_icons: 0.7.4


dependecy_overrides:


#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/app_icon.png"


flutter:
  uses-material-design: true
#  assets:
#    - assets/

#  fonts:
#    - family: Montserrat
#      fonts:
#        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
#        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
#          weight: 700